name: Build

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest
          - windows-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@master

      - name: upgrade compilers for macos
        if: matrix.os == 'macOS-latest'
        run: |
          sudo rm -rf /Library/Developer/CommandLineTools
          xcode-select --install
          CXX=clang++ brew reinstall gcc@8

      - name: upgrade compilers for ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y gcc-8 g++-8
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 20
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 20

      - name: debug
        run: |
          which g++
          which gcc
          g++ --version
          gcc --version
          printenv

      - name: configure
        if: matrix.os != 'windows-latest'
        run: |
          mkdir build
          cd build
          CC=/usr/bin/gcc CXX=/usr/bin/g++ cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: configure
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p build/Release
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/c/ProgramData/Chocolatey/bin/gcc -DCMAKE_CXX_COMPILER=/c/ProgramData/Chocolatey/bin/g++ 

      - name: build
        if: matrix.os != 'windows-latest'
        run: |
          cd build
          CC=/usr/bin/gcc CXX=/usr/bin/g++ cmake --build . --target install --config Release
    
      - name: build
        if: matrix.os == 'windows-latest'
        run: |
          cd build
          cmake --build . --target install --config Release

      - name: test
        run: |
          ./bin/console-gen make:command --name todo:list --class TodoList

      - uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin
